name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        build-tools: 31.0.0
        ndk: 21.4.7075529

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Override org.gradle.java.home if set
      run: |
        if grep -q "org.gradle.java.home" gradle.properties; then
          sed -i '/org.gradle.java.home/d' gradle.properties
        fi

    - name: Build with Gradle
      run: ./gradlew build

    - name: Print environment variables
      run: printenv

    - name: Print Java version
      run: java -version

    - name: Print JAVA_HOME
      run: echo $JAVA_HOME

    - name: Print Gradle properties
      run: cat gradle.properties
